baseurl = "https://mobileorg.github.io"
languageCode = "en-gb"
title = "MobileOrg"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "MobileOrg"
	description = "Org mode on your iOS device"
	copyright = "Released under the GPL v3 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/MobileOrg/mobileorg"

	version = "1.7.2"
	logo = "img/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "MobileOrg"
	email   = ""


[[menu.main]]
	name   = "MobileOrg"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Features"
	url    = "features/"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "documentation/"
	weight = 20

[[menu.main]]
	name   = "FAQ"
	url    = "faq/"
	weight = 30

[[menu.main]]
	name   = "Credits"
	url    = "credits/"
	weight = 40

[[menu.main]]
	name   = "Release Notes"
	url    = "release-notes/"
	weight = 50

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
